export default [
    {
        ignores: [
            "js/vue/**",
            "**/*.min.js",
            "node_modules/**",
        ],
    },
    {
        files: ["js/**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                localStorage: "readonly",
                fetch: "readonly",
                Headers: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                CustomEvent: "readonly",
                AbortController: "readonly",
                IntersectionObserver: "readonly",
                HTMLVideoElement: "readonly",
                HTMLCanvasElement: "readonly",
                HTMLElement: "readonly",
                CSS: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                Blob: "readonly",
                File: "readonly",
                Element: "readonly",
                SVGElement: "readonly",
                MathMLElement: "readonly",
                Image: "readonly",
                ImageData: "readonly",
                ResizeObserver: "readonly",
                MutationObserver: "readonly",
                MouseEvent: "readonly",
                DataTransfer: "readonly",
                DragEvent: "readonly",
                Event: "readonly",
                FormData: "readonly",
                atob: "readonly",
                btoa: "readonly",
                confirm: "readonly",
                navigator: "readonly",
                performance: "readonly",
                process: "readonly",
            },
        },
        rules: {
            "no-undef": "error",
            "no-unreachable": "error",
            "no-cond-assign": "error",
            "no-control-regex": "error",
            "no-unused-expressions": "error",
            "no-useless-escape": "error",
            "no-dupe-keys": "error",
            "no-constant-condition": "error",
            "no-unused-vars": [
                "warn",
                {
                    argsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                    caughtErrorsIgnorePattern: "^_",
                },
            ],
        },
    },
];
